language: java
sudo: false
jdk:
  - openjdk8
env:
  - COVERALLS_REPO_TOKEN=KSAlJaw1Jrb5Fj41wELVzpyw9jbajaEBC
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - gradle test
after_success:
  - gradle jacocoTestReport coveralls